### ISSUE TITLE
h5py dataset.value deprecated

### ISSUE THREAD

**Issue by V-Xing** [clapeyre/h5nav#3]
The following deprecation warning often comes up:

/scratch/csg/xing/pyenvs/xing/lib/python3.6/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)

Replacing all the .value by [()] should solve this.

**Comment by clapeyre** [comment]
Thanks. Should be fixed by 2842e8b
